name: Publish npm package

on:
    push:
        tags:
            - 'v*'  # Run when a version tag (e.g., v1.0.0) is pushed        
    workflow_dispatch: {}

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: "https://registry.npmjs.org"

            - name: Install dependencies
              run: npm ci

            - name: Build lib package
              run: npm run compile && npm run lib

            - name: Publish to npm
              working-directory: ./lib
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
